blpass: added dependencies check

diff --git a/blpass b/blpass
--- a/blpass
+++ b/blpass
@@ -23,11 +23,15 @@ main() {
    elif [ -e /etc/debian_version ]; then
       $sudo apt-get -y update
 			$sudo apt-get -y install git bash-completion build-essential cmake libcurl4 libcurl4-openssl-dev libssl-dev libxml2 libxml2-dev libssl1.1 pkg-config ca-certificates xclip
-
    else
 	   echo "Your distribution is not supported yet!"
 	   exit 23
    fi
+
+	 if [ $? -ne 0 ];then
+		 echo "Dependencies not successfully installed! Aborting"
+		 exit 28
+	 fi
 
    cd ${srcdir}
    if [ ! -d lastpass-cli ]; then
