added some checks to bsqlite3

diff --git a/bsqlite3 b/bsqlite3
--- a/bsqlite3
+++ b/bsqlite3
@@ -4,9 +4,11 @@ operator=$(whoami)
 srcdir=/opt/src
 nproc=$(grep -c ^processor /proc/cpuinfo)
 sudo="sudo"
-version="3.39.0"
+version="3.39.3"
 
 main() {
+
+	checkAlready
 
 	uid=$(id -u)
 	if [ "${uid}" = "0" ]; then
@@ -50,6 +52,19 @@ main() {
 	make sqlite3 sqldiff -j $nproc
 	$sudo make install
 
+}
+
+checkAlready() {
+	echo -n "sqlite3: "
+  # sqlite3 installed at all?
+	which sqlite3 || { echo "sqlite3 not found!" ; exit 60 ; }
+	# extract current sqlite version
+	current=$(sqlite3 --version | cut -d' ' -f 1)
+	if [ "${current}" = "${version}" ] ; then
+		echo "Version ${version} is already installed!"
+		echo "Please set 'version' variable in script and try again"
+		exit 23
+	fi
 }
 
 main $@
